[package]
name = "rtiles"
description = "3D Tiles caching server"
authors = ["Nikolay Ishiev <ishiev@primetver.ru>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
serde = { version = "1.0", features = ["derive"] }
moka = { version = "0.7", features = ["future"] }
reqwest = "0.11"
log     = "^0"