[default]
address = "127.0.0.1"
port = 8000
base_path = "/3d/models/"
log_level = "debug"

[default.access]
server = "https://httpbin.org/anything"
cache_ttl = 1800
cache_tti = 300

[default.storage]
root = "data"
max_age = 1800