[default]
address = "127.0.0.1"
port = 8000
base_path = "/3d"
log_level = "normal"

[default.access]
server = "https://httpbin.org/anything"
cache_ttl = 1800         # 30 min
cache_tti = 300          # 5 мин

[default.storage]
root = "data"
max_age = 1800            # 30 min
cache_size = 500          # 500 MB
