[default]
address = "127.0.0.1"
port = 8000
base_path = "/3d"
log_level = "normal"

[default.access]
server = "https://httpbin.org/anything"
cache_ttl = 1800
cache_tti = 300

[default.storage]
root = "data"
max_age = 1800

[default.cache]
size = 50           # 50 MB
cache_ttl = 86400   # 24 hours
cache_tti = 14400   # 4 hours
